version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:739275474016:task-definition/onais-devops-task-definition:4"
        LoadBalancerInfo:
          ContainerName: "onais-devops-container"
          ContainerPort: 3000